### ISSUE TITLE
Get rid of the sidebar (partially?)

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#173]
At least we could delete the stuff that people now find in the menu:

![screen shot 2015-12-07 at 18 33 50](https://cloud.githubusercontent.com/assets/1711357/11634493/1b1216ae-9d11-11e5-8113-efff2910f1d7.png)

That would make it all a bit more sleek and easier to read. Wdyt? 

Ping @apertoclaudi?

**Comment by alicetragedy** [comment]
I'm open to thinking about this as an alternative solution, but I think the idea of the sidebar is a way to see where you are within the site and to access an alternative menu without using the burger button (which can be sort of disruptive). Unless we know exactly what kind of changes we want to do, I wouldn't invest too much time or effort into changing it since it's a low priority issue, but I'd love to see if claudi has any ideas about it.

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/192
I'm closing this!
