### ISSUE TITLE
explain stars on sponsor's logos

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code#252]
most sponsors don't know what the stars on their logos mean, so we should definitely explain that somewhere. maybe @anasofiapinho you could take care of that and add it to the donation site or somewhere? the stars indicate how often the sponsors have donated to rgsoc (so 3 stars means 3-year-sponsor)

**Comment by anasofiapinho** [comment]
@anikalindtner I have created a PR and added a small phrase on top of the logos saying what the stars are about. I also noticed that if people place the mouse on top of each star, they will see the year that the company sponsored RGSoC. I am not sure if this looks very good, especially because of the spacing. If anyone else would like to take a look, please do!
@troubalex I know you are an UI expert, would you mind to take a look at this if you have time? :)

Link for the pull request:
https://github.com/rails-girls-summer-of-code/summer-of-code/pull/259

<img width="1440" alt="screen shot 2016-08-06 at 22 24 33" src="https://cloud.githubusercontent.com/assets/3285560/17459152/dcc9262a-5c24-11e6-8dff-859b41df31a6.png">

**Comment by troubalex** [comment]
I only have two small nitpicks, which are partly a matter of taste.
1. I'd drop the star icon in front. It feels unnecessary, and looks a bit crammy.
2. I'd then move the sentence to the bottom, right below the last row of Bronze sponsors. The information is less important than the sponsors themselves, and will demand less attention down there. That is assuming that it's more of an "FYI" rather than a selling point on behalf of the sponsors.

Does that make sense?

**Comment by anasofiapinho** [comment]
Hey @troubalex,
Thanks for your feedback. I also agree with moving that phrase to the bottom. I was trying to see if it could be put on top so that there was a bigger chance that people would see it. But, yeah, it's best to have it on the bottom (I also removed the star), because it was creating some "visual conflict" with the logos, and the sponsors' logos are more important than that.

Thanks again! <3

I don't have any other changes to make here, @anikalindtner. If everyone agrees, you can merge this.

**Comment by alicetragedy** [comment]
Note: if you hover on the stars it actually shows which year the sponsor has sponsored (alt text) ;) Nevertheless I will merge @anasofiapinho's PR!

**Comment by alicetragedy** [comment]
fixed in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/259. Closing!
