### ISSUE TITLE
Add conferences' logos to the website

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/summer-of-code#267]
We would like to add logos of conferences which support us this year to the footer, like it was implemented in 2013: http://2013.railsgirlssummerofcode.org/

Logos of conferences 2016 are available here:
https://github.com/rails-girls-summer-of-code/summer-of-code/tree/gh-pages/img/blog/2016/conferences

NOTE: 
- rubyconf-au-logo might change;
- goto-berlin-logo should not be announced yet.

**Comment by klappradla** [comment]
Taking a look at this now @mkalininait, but I got some tiny questions:

1) what should be shown?

> goto-berlin-logo should not be announced yet.

means that I should skip this one for the footer?

2) stars?
I suppose the conferences don't get _stars_ in their logos (since I don't find information on when they've been part of RGSoC)?

3) sponsor page
Should the conferences also be listed on the [sponsors page](http://railsgirlssummerofcode.org/sponsors/)?

**Comment by klappradla** [comment]
Another tiny question: the conferences don't get *stars* in their logos I suppose (it would not fit the space anyways) as there's no information on how often they've been part of RGSoC yet?
