### ISSUE TITLE
Small site updates to wrap up 2017

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#441]
- [x] update timeline (PR in [here](https://github.com/rails-girls-summer-of-code/summer-of-code/pull/442))
- [x] update campaign page: remove overview of teams sponsored, change copy accordingly
- [x] update blurbs at the start of all guides
- [x] remove diversity tickets donations from list of donations
- [x] archive donations (see [internal documentation](https://github.com/rails-girls-summer-of-code/organization/wiki/Archiving-old-donations))

**Comment by alicetragedy** [comment]
@inescoelho I know you're eager to help, and this is all time-sensitive — maybe you'd be up for helping with these tasks? It's mainly about trying to wrap-up 2017 so we can officially kick off 2018. The donation archiving will require access for you to heroku and to the campaign app I mentioned in the call, I can give you access to those when/if you need them.

**Comment by inescoelho** [comment]
Thanks for the suggestion, Laura! I might have time for this at the end of the week! Count with me, if no one else picks this up before that ;)

**Comment by alicetragedy** [comment]
Let me know if you are still interested in this @inescoelho and if you would have time :) The guides are slowly taken care of already since I'm updating some of the copy right now, but the rest will still need doing at some point ;)

**Comment by inescoelho** [comment]
@alicetragedy, I've just submitted a PR with most of the changes -> #471

However, I've encountered some problems with the archiving of the donations. I will reach you out on slack, as it is urgent to fix this.

Besides the list of conferences, this PR also updates references for the 2017 campaign (such as in the blog's sidebar). I also took the liberty to clean the list of sponsors from the website. I opt not to put any sponsor in the 2018 edition because I believe you want to update the information from Travis CI and change it for Travis Foundation, instead? And also, I don't have information for the other sponsors, as they are new. So, if you merge this PR, please don't forget to add information regarding the 2018 sponsors! ;) Also, I didn't update the text on the campaign page, I feel that that should be the responsibility of whoever opens the campaign?

All the changes were made in separate commits, so feel free to cherry-pick the commits if needed!

**Comment by alicetragedy** [comment]
Closing this issue as it's been fixed over the last couple of weeks. :) Thank you @inescoelho for making this happen!
