### ISSUE TITLE
Conference List

### ISSUE THREAD

**Issue by inescoelho** [rails-girls-summer-of-code/summer-of-code#470]
Cleaning up the website for 2018, I realized that, although we keep a list of the conferences every year, the majority of the information about the conference is hard-coded in the conferences page and lost with the cleaning. We could reformulate this to be more similar to the sponsor's page where instead of using a MD file we use HTML and the information is read from the data file using Rails.

**Comment by alicetragedy** [comment]
I totally agree — I'd love to have something like this for the conferences, it makes a lot of sense. In fact, we already have YAML files for past conferences with their url, id and name so all we need to get started is to add a way of iterating through these (found in `_data/conferences.yml`) on the conferences page (`students/conferences.md`).
I'm going to add relevant tags so that we can get help from people (volunteers or new contributors) if needed 🎉

**Comment by alicetragedy** [comment]
done in https://github.com/rails-girls-summer-of-code/summer-of-code/pull/557. closing!
